version: "3.8"


services:
  postgres:
    image: arm64v8/postgres:latest
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    
  pgAdmin:
    image: dpage/pgadmin4:latest
    ports: 
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dbuser@bbp.com
      - PGADMIN_DEFAULT_PASSWORD=password
